### ISSUE TITLE
Google Cloud: Enhance to generate Word Document (instead of text)

### ISSUE THREAD

**Issue by alan-walsh** [indiana-university/automated-transcription-service#7]
Generate a nicely formatted Word document like we do in the ATS processed for GCP: https://github.com/indiana-university/automated-transcription-service/blob/main/google/sttparser.py

Note; this may be a larger task, coordinate and spec as appropriate before starting.

**Comment by pcberg** [comment]
TODOs:
* Verify timestamp logic, on -s (speaker mode) it's printing the first timestamp twice and then is off by 1 (compare to AWS version for where it shows correctly)
* Look into word confidence scoring without -s (speaker mode). Is it in the json / possible?
* Verify word confidence scoring is conditional, not every gc transcription has it. Make sure it doesn't fail the python script

**Comment by pcberg** [comment]
Closing issue, I tested/resolved thetwo bullet points of my last comment. I also added a summary header like we have in the AWS docx output.
